"""Add seller_contact_info to Transaction model

Revision ID: aec310b938de
Revises: a4a21fcf2401
Create Date: 2025-04-23 21:36:14.895401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec310b938de'
down_revision = 'a4a21fcf2401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_contact_info', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('seller_contact_info')

    # ### end Alembic commands ###
